### PR TITLE
[MIA-159]: includes feature to download csvs

### PR DESCRIPTION
**Pull request by scottqueen-bixal**
closes https://cm-jira.usa.gov/browse/MIA-159

## Description

- Sets a file as Blob  and assigns it as ObjectURL to our download button
- Includes Cypress test includes checking on the download element to confirm the file is actually downloaded

## How to test

- Verify cypress test is passing in pipeline
- Navigate to the [waiver page](https://federalist-c275c827-2779-42ff-ac19-0331ebcacca9.app.cloud.gov/preview/gsa/made-in-america/feature/csv-download/waivers/)
- Click "Download .CSV File" button
- Confirm file downloaded is named `waivers.csv`
- Open `waivers.csv` file on your local machine
- Confirm that cells are filled with our [data](https://github.com/GSA/made-in-america-data/blob/main/waivers.csv)

To prepare for code review, please follow the following checks.

- [x] branch has detailed description of work/updates
- [x] title format follows: `[Ticket Number] : Brief statement describing what this pull request solves`.
- [x] passed all integrated testing
- [x] pipeline has completed successfully
- [x] federalist preview has been generated
- [x] code review/design review requested as appropriate
- [x] branch/preview link updated in ticket

### CODE REVIEW

**Comment by scottqueen-bixal** [comment]
@clmedders tagging you on this early to start having a look at the cypress test

**Review by kennethedwards-bixal — APPROVED** [review]

**Review by jefffortune — CHANGES_REQUESTED** [review]
@kennethedwards-bixal  can you look into a issue I am having. When I click the download button I am only receiving a csv with a header row.

**Review by jefffortune — APPROVED** [review]

**Review by jefffortune — CHANGES_REQUESTED** [review]
@clmedders I am getting failed test for status update. Can you please advise the issue that is is having?

**Comment by clmedders** [comment]
@jefffortune I updated the package-lock.json file.  the plugin that was added for the cypress to check the download needed it, when I was looking at it yesterday it was giving me a path error.  Also, I rebuilt the search-app on the waiver page.  The test was failing because it could not find the data-test attribute `data-test="status-date"` which is what the test is looking for.

I will look into the issue you mentioned in the ticket about it not completing and you had to close it out again.  Maybe this can get fixed with added the screenshot on a failed test but will do more digging on anything I can add to fix that issue.

I also added more info and screenshots of my output to the Jira ticket!

**Pull request merged**
