### PR TITLE
[mia-173] HTML-proofer version update (3.19.2 - 3.19.3)

### PR DESCRIPTION
**Pull request by clmedders**
## Description

This Pr updates HTML-proofer version based on dependabot suggestions.

closes out PR: https://github.com/GSA/made-in-america/pull/128

## How to test

- npm install
- bundle install
- npm run stat 
- then spilt terminal 
- npm run htmlproofer

## Additional information

Include any of the following (as necessary):

- html proofer has been updated to the latest version, Gemfile.lock is the file that was updated in this PR.

To prepare for code review, please follow the following checks.

- [x] branch has detailed description of work/updates
- [x] title format follows: `[Ticket Number] : Brief statement describing what this pull request solves`.
- [x] passed all integrated testing
- [x] pipeline has completed successfully
- [x] federalist preview has been generated
- [x] code review/design review requested as appropriate
- [x] branch/preview link updated in ticket

### CODE REVIEW

**Comment by scottqueen-bixal** [comment]
because this is a gem rather than a node module, we need to include `bundle install` in our test steps to ensure we are getting the latest gems from our lock reference

**Comment by clmedders** [comment]
@scottqueen-bixal got it... made the update in the testing steps!

**Comment by scottqueen-bixal** [comment]
@clmedders I see that you've included the `Gemfile.lock` but I don't see the `Gemfile` with the updated dependency reference?

**Comment by scottqueen-bixal** [comment]
> @clmedders I see that you've included the `Gemfile.lock` but I don't see the `Gemfile` with the updated dependency reference?

hmm - looks like we `gem "html-proofer", "~> 3.19"` which I guess pulls in the patch to the lockfile once the bundle is installed again... I think we are good on this one then

**Review by scottqueen-bixal — APPROVED** [review]

**Pull request merged**
